CLAIMER ConstraintClaimer
file CONVERGED_DISTANCES
FULLATOM
CENTROID
SKIP_REDUNDANT 0
FILTER_WEIGHT  1.00
FILTER_NAME converged_distances
END_CLAIMER

CLAIMER ConstraintClaimer
file FILTERED_CONTACTMAPS
COMBINE_RATIO 2
FULLATOM
CENTROID
SKIP_REDUNDANT 0
FILTER_WEIGHT  1.00
FILTER_NAME filtered_contactmaps
END_CLAIMER


