#!/bin/csh

set PATH_TO_EXE=/vol/ek/ravehb/rosetta/svn_mini/mini/bin
set PATH_TO_DB=/vol/ek/ravehb/rosetta/svn_mini/minirosetta_database/

#rosetta command line
$PATH_TO_EXE/FlexPepDocking.linuxgccrelease -database $PATH_TO_DB @prepack_flags > prepack.log

mv start_0001.pdb start.ppk.pdb
mv score.sc ppk.score.sc

echo "Pre-packing done!"
echo
