--- 
address: 127.0.0.1
port: 3002
rackup: config-public.ru 
environment: production
timeout: 30
wait: 30
max_conns: 1024
max_persistent_conns: 512
daemonize: true
threaded: true
threadpool-size: 20
tag: demos-public
