CLAIMER MembraneTopologyClaimer
END_CLAIMER
CLAIMER ConstraintClaimer
FILE /home/hirstsj/rosetta/benchmark_membrane/extended_mp_benchmark_set/protocol_capture/demo/input_files/1U19A_s00_b000_0000.cst
END_CLAIMER
