#!/bin/bash

#rosetta command line

# MPI launch using 5 processors
#
# mpirun -n 5 /home/andrew/rosetta/SVN/mini_mpims/mini/bin/mpi_msd.mpi.linuxgccrelease -entity_resfile input_files/entity.resfile -fitness_file input_files/fitness.daf  -ms::pop_size 100 -ms::generations 210  -ms::numresults 1 -no_his_his_pairE -ms::fraction_by_recombination 0.02 -database /home/andrew/minirosetta_database


# Regular launch using 1 processor
#
/home/andrew/rosetta/SVN/mini_mpims/mini/bin/mpi_msd.default.linuxgccrelease -entity_resfile input_files/entity.resfile -fitness_file input_files/fitness.daf  -ms::pop_size 100 -ms::generations 210  -ms::numresults 1 -no_his_his_pairE -ms::fraction_by_recombination 0.02 -database /home/andrew/minirosetta_database
