#!/bin/bash -x
###
###
### This file is part of the CS-Rosetta Toolbox and is made available under
### GNU General Public License
### Copyright (C) 2011-2012 Oliver Lange
### email: oliver.lange@tum.de
### web: www.csrosetta.org
###
### This program is free software: you can redistribute it and/or modify
### it under the terms of the GNU General Public License as published by
### the Free Software Foundation, either version 3 of the License, or
### (at your option) any later version.
###
### This program is distributed in the hope that it will be useful,
### but WITHOUT ANY WARRANTY; without even the implied warranty of
### MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
### GNU General Public License for more details.
###
### You should have received a copy of the GNU General Public License
### along with this program.  If not, see <http://www.gnu.org/licenses/>.
###
###
NSLOTS=24
#SBATCH -n 24
#SBATCH --time=0:30:00
#SBATCH -J test_csrosetta
### start of jobscript

module load openmpi/gcc

LOGS=logs_`echo $SLURM_JOB_ID | awk -v FS="." '{print $1}'`
mkdir -p $LOGS

## have NSLOTS - 3 worker processes -- determines number of structures per generation...
NSTRUCT=`echo $NSLOTS | awk '{print $1-3}'`

echo "running on $NSLOTS cpus ..."
EXE=$CM_EXECUTEABLE.$CM_EXEC_EXT
CMDLINE="-out:level 300 -mute all_high_mpi_rank_filebuf -out:mpi_tracer_to_file $LOGS/log -database $CM_ROSETTA_DATABASE $CM_COMMANDLINE"
CYCLES=$CM_AUTO_NSTRUCT"-run:test_cycles -jd2::mpi_timeout_factor -1"
$MPI_RUN -n $NSLOTS $EXE $CMDLINE $CYCLES
