#!/bin/bash -x
###
###
### This file is part of the CS-Rosetta Toolbox and is made available under
### GNU General Public License
### Copyright (C) 2011-2012 Oliver Lange
### email: oliver.lange@tum.de
### web: www.csrosetta.org
###
### This program is free software: you can redistribute it and/or modify
### it under the terms of the GNU General Public License as published by
### the Free Software Foundation, either version 3 of the License, or
### (at your option) any later version.
###
### This program is distributed in the hope that it will be useful,
### but WITHOUT ANY WARRANTY; without even the implied warranty of
### MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
### GNU General Public License for more details.
###
### You should have received a copy of the GNU General Public License
### along with this program.  If not, see <http://www.gnu.org/licenses/>.
###
###
#MSUB -l nodes=1:ppn=8
#MSUB -l walltime=0:59:00
#MSUB -N test_csrosetta
### start of jobscript
NSLOTS=${NSLOTS:=`cat "$PBS_NODEFILE" | wc -l`}
NSTRUCT=$( echo $NSLOTS | awk '{print $1-3}' )
cd $PBS_O_WORKDIR
echo "workdir: $PBS_O_WORKDIR"
LOGS=logs_`echo $PBS_JOBID | awk -v FS="." '{print $1}'`
mkdir -p $LOGS

echo "running on $NSLOTS cpus ..."
EXE=$CM_EXECUTEABLE.$CM_EXEC_EXT
CMDLINE="-out:level 300 -mute all_high_mpi_rank_filebuf -out:mpi_tracer_to_file $LOGS/log -database $CM_ROSETTA_DATABASE $CM_COMMANDLINE"
CYCLES=$CM_AUTO_NSTRUCT" -run:test_cycles -jd2::mpi_timeout_factor -1"
mpiexec -np $NSLOTS $EXE $CMDLINE $CYCLES
