#!/bin/csh

set PATH_TO_EXE=/vol/ek/liorz06/miniRosettaWorkspace/mini/bin/
set PATH_TO_DB=/vol/ek/liorz06/miniRosettaWorkspace/rosetta_database

#rosetta command line
$PATH_TO_EXE/FlexPepDocking.linuxgccrelease -database $PATH_TO_DB @flags

echo "FlexPepDock Ab-initio done!"
echo
