#!/bin/bash -x
NSLOTS=24
#SBATCH -n 24
#SBATCH --time=0:30:00
#SBATCH -J test_csrosetta

module load openmpi/gcc

LOGS=logs_`echo $SLURM_JOB_ID | awk -v FS="." '{print $1}'`
mkdir -p $LOGS


echo "running on $NSLOTS cpus ..."
EXE=" /home/zhezhang/rosetta_vanilla/rosetta_source/bin/r_play_with_etables.mpi.linuxgccrelease "
CMDLINE="-out:level 300 -mute all_high_mpi_rank_filebuf -out:mpi_tracer_to_file $LOGS/log -database /home/zhezhang/rosetta_vanilla/rosetta_database  @flags_docking_replica @flags_replica_dock -parser:protocol dock_cen_7.xml"
CYCLES="-run:test_cycles -jd2::mpi_timeout_factor -1"
$MPI_RUN -n $NSLOTS $EXE $CMDLINE $CYCLES

