#!/bin/bash
###
###
### This file is part of the CS-Rosetta Toolbox and is made available under
### GNU General Public License
### Copyright (C) 2011-2012 Oliver Lange
### email: oliver.lange@tum.de
### web: www.csrosetta.org
###
### This program is free software: you can redistribute it and/or modify
### it under the terms of the GNU General Public License as published by
### the Free Software Foundation, either version 3 of the License, or
### (at your option) any later version.
###
### This program is distributed in the hope that it will be useful,
### but WITHOUT ANY WARRANTY; without even the implied warranty of
### MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
### GNU General Public License for more details.
###
### You should have received a copy of the GNU General Public License
### along with this program.  If not, see <http://www.gnu.org/licenses/>.
###
###

if [ "$MPI_RUN" == "" ]; then
   MPI_RUN=mpiexec
fi

PREFIX=""
if [ "$1" == "-n" ]; then
   PREFIX="$MPI_RUN -n $2"
fi

$PREFIX $CM_EXECUTEABLE.$CM_EXEC_EXT -out:level 300 -out:file:silent decoys.out $CM_COMMANDLINE -database $CM_ROSETTA_DATABASE
