// (c) Copyright Rosetta Commons Member Institutions.
// (c) This file is part of the Rosetta software suite and is made available under license.
// (c) The Rosetta software is developed by the contributing members of the Rosetta Commons.
// (c) For more information, see http://www.rosettacommons.org. Questions about this can be
// (c) addressed to University of Washington UW TechTransfer, email: license@u.washington.edu.
#ifndef coreall
#define coreall value

#include "all.fwd.hh"

#include "utility/pointer/owning_ptr.hh"

#include "core/types.hh"
#include "core/chemical/types.hh"
#include "core/id/types.hh"
#include "core/kinematics/types.hh"
#include "core/optimization/types.hh"
#include "core/pack/types.hh"
#include "core/scoring/types.hh"
#include "core/scoring/hbonds/types.hh"

#include "core/chemical/AA.hh"
#include "core/chemical/AtomICoor.hh"
#include "core/chemical/AtomType.hh"
#include "core/chemical/AtomTypeSet.hh"
#include "core/chemical/ChemicalManager.hh"
#include "core/chemical/MMAtomType.hh"
#include "core/chemical/MMAtomTypeSet.hh"
#include "core/chemical/Patch.hh"
#include "core/chemical/PatchOperation.hh"
#include "core/chemical/residue_io.hh"
#include "core/chemical/ResidueConnection.hh"
#include "core/chemical/ResidueSelector.hh"
#include "core/chemical/ResidueSupport.hh"
#include "core/chemical/ResidueType.hh"
#include "core/chemical/ResidueTypeSet.hh"
#include "core/chemical/util.hh"
#include "core/chemical/VariantType.hh"
#include "core/conformation/Atom.hh"
#include "core/conformation/Conformation.hh"
#include "core/conformation/Residue.hh"
#include "core/conformation/ResidueFactory.hh"
#include "core/graph/DistanceGraph.hh"
#include "core/graph/find_neighbors.hh"
#include "core/graph/Graph.hh"
#include "core/graph/PointGraph.hh"
#include "core/graph/PointGraphData.hh"
#include "core/graph/UpperEdgeGraph.hh"
#include "core/id/AtomID.hh"
#include "core/id/AtomID_Map.hh"
#include "core/id/AtomID_Map.Pose.hh"
#include "core/id/AtomID_Mask.hh"
#include "core/id/DOF_ID.hh"
#include "core/id/DOF_ID_Map.hh"
#include "core/id/DOF_ID_Mask.hh"
#include "core/id/TorsionID.hh"
#include "core/init.hh"
#include "core/io/database/open.hh"
#include "core/io/pdb/file_data.hh"
#include "core/io/pdb/pdb_dynamic_reader.hh"
#include "core/io/pdb/pose_io.hh"
#include "core/kinematics/all.hh"
#include "core/kinematics/AtomPointers.hh"
#include "core/kinematics/AtomTree.hh"
#include "core/kinematics/CAlpha.hh"
#include "core/kinematics/constants.hh"
#include "core/kinematics/DomainMap.hh"
#include "core/kinematics/Edge.hh"
#include "core/kinematics/FoldTree.hh"
#include "core/kinematics/Jump.hh"
#include "core/kinematics/MoveMap.hh"
#include "core/kinematics/RT.hh"
#include "core/kinematics/Stub.hh"
#include "core/kinematics/tree/Atom.hh"
#include "core/kinematics/tree/Atom_.hh"
#include "core/kinematics/tree/BondedAtom.hh"
#include "core/kinematics/tree/JumpAtom.hh"
#include "core/kinematics/util.hh"
#include "core/mm/mm_torsion_library.hh"
#include "core/optimization/atom_tree_minimize.hh"
#include "core/optimization/AtomNode.hh"
#include "core/optimization/AtomTreeMinimizer.hh"
#include "core/optimization/AtomTreeMultifunc.hh"
#include "core/optimization/DOF_Node.hh"
#include "core/optimization/Minimizer.hh"
#include "core/optimization/MinimizerMap.hh"
#include "core/optimization/MinimizerOptions.hh"
#include "core/optimization/Multifunc.hh"
// #include "core/options/after_opts.hh"
// #include "core/options/all.hh"
// #include "core/options/keys/all.hh"
// #include "core/options/keys/OptionKeys.cc.gen.hh"
// #include "core/options/keys/OptionKeys.hh"
// #include "core/options/keys/OptionKeys.hh.gen.hh"
// #include "core/options/option.cc.gen.hh"
#include "core/options/option.hh"
#include "core/pack/all.hh"
// #include "core/pack/annealer/DebuggingAnnealer.hh"
// #include "core/pack/annealer/FixbbSimAnnealer.hh"
// #include "core/pack/annealer/RotamerAssigningAnnealer.hh"
// #include "core/pack/annealer/SimAnnealerBase.hh"
#include "core/pack/interaction_graph/AminoAcidNeighborSparseMatrix.hh"
#include "core/pack/interaction_graph/DensePDInteractionGraph.hh"
#include "core/pack/interaction_graph/InteractionGraphBase.hh"
// #include "core/pack/interaction_graph/PDInteractionGraph.hh"
#include "core/pack/interaction_graph/PrecomputedInteractionGraph.hh"
#include "core/pack/interaction_graph/SparseMatrixIndex.hh"
#include "core/pack/pack_rotamers.hh"
#include "core/pack/packer_neighbors.hh"
#include "core/pack/rotamer_set/AminoAcidRotamerSet.hh"
#include "core/pack/rotamer_set/BumpSelector.hh"
// #include "core/pack/rotamer_set/NucleicAcidRotamerSet.hh"
#include "core/pack/rotamer_set/RotamerSet.hh"
#include "core/pack/rotamer_set/RotamerSetFactory.hh"
#include "core/pack/rotamer_set/RotamerSets.hh"
#include "core/pack/rotamer_trials.hh"
#include "core/pack/task/PackerTask.hh"
#include "core/pack/task/PackerTask_.hh"
#include "core/pack/task/RotamerOptions.hh"
#include "core/pack/task/RotamerOptions_.hh"
#include "core/pack/task/RotamerOptionsFactory.hh"
#include "core/pack/task/TaskFactory.hh"
#include "core/pose/Pose.hh"
// #include "core/pose/PScene.hh"
#include "core/scoring/CachedData.hh"
#include "core/scoring/constants.hh"
#include "core/scoring/ContextGraph.hh"
#include "core/scoring/ContextGraphFactory.hh"
#include "core/scoring/ContextGraphTypes.hh"
#include "core/scoring/dunbrack/RotamerLibrary.hh"
#include "core/scoring/Energies.hh"
#include "core/scoring/EnergyGraph.hh"
#include "core/scoring/etable/atom_pair_energy_inline.hh"
#include "core/scoring/etable/count_pair/CountPair1BC3.hh"
#include "core/scoring/etable/count_pair/CountPair1BC4.hh"
#include "core/scoring/etable/count_pair/CountPairAll.hh"
#include "core/scoring/etable/count_pair/CountPairCrossover3.hh"
#include "core/scoring/etable/count_pair/CountPairCrossover4.hh"
#include "core/scoring/etable/count_pair/CountPairFunction.hh"
#include "core/scoring/etable/Etable.hh"
#include "core/scoring/etable/EtableEnergy.hh"
#include "core/scoring/etable/EtableOptions.hh"
#include "core/scoring/etable/etrie/CountPairData_1_1.hh"
#include "core/scoring/etable/etrie/CountPairData_1_2.hh"
#include "core/scoring/etable/etrie/CountPairData_1_3.hh"
#include "core/scoring/etable/etrie/EtableAtom.hh"
#include "core/scoring/etable/etrie/TrieCountPair1BC3.hh"
#include "core/scoring/etable/etrie/TrieCountPair1BC4.hh"
#include "core/scoring/etable/etrie/TrieCountPairAll.hh"
#include "core/scoring/hbonds/constants.hh"
#include "core/scoring/hbonds/create_poly.hh"
#include "core/scoring/hbonds/hbonds.hh"
#include "core/scoring/hbonds/hbonds_geom.hh"
#include "core/scoring/hbonds/HBondSet.hh"
#include "core/scoring/methods/ChainbreakEnergy.hh"
#include "core/scoring/methods/ContextDependentTwoBodyEnergy.hh"
#include "core/scoring/methods/ContextIndependentOneBodyEnergy.hh"
#include "core/scoring/methods/ContextIndependentTwoBodyEnergy.hh"
#include "core/scoring/methods/DunbrackEnergy.hh"
#include "core/scoring/methods/EnergyMethod.hh"
#include "core/scoring/methods/EnergyMethodOptions.hh"
#include "core/scoring/methods/HBondEnergy.hh"
#include "core/scoring/methods/Methods.hh"
#include "core/scoring/methods/PairEnergy.hh"
#include "core/scoring/methods/RamachandranEnergy.hh"
#include "core/scoring/NeighborList.hh"
#include "core/scoring/PairEPotential.hh"
#include "core/scoring/ProteinTorsion.hh"
#include "core/scoring/Ramachandran.hh"
#include "core/scoring/residue_pair_energy.hh"
#include "core/scoring/sasa.hh"
#include "core/scoring/ScoreFunction.hh"
#include "core/scoring/ScoreFunctionInfo.hh"
#include "core/scoring/ScoreFunctionParameter.hh"
#include "core/scoring/ScoreFunctionVariant.hh"
#include "core/scoring/ScoreType.hh"
#include "core/scoring/ScoringManager.hh"
#include "core/scoring/TenANeighborGraph.hh"
#include "core/scoring/trie/RotamerDescriptor.hh"
#include "core/scoring/trie/RotamerTrie.hh"
#include "core/scoring/trie/RotamerTrieBase.hh"
#include "core/scoring/trie/trie_vs_path.hh"
#include "core/scoring/trie/trie_vs_trie.hh"
#include "core/scoring/trie/TrieCollection.hh"
#include "core/scoring/trie/TrieCountPairBase.hh"
#include "core/util/basic.hh"
#include "core/util/interpolate.hh"
#include "core/util/prof.hh"
#include "core/util/Tracer.hh"

#endif
