#!/bin/bash

# Making sequence_tolerance resfiles
# GB1 Fold Stability Tolerance
scripts/seqtol_resfile.py input_files/2QMT/2QMT.pdb "ALLAA" A:5 A:7 A:16 A:18 A:18 A:30 A:33
# PDZ Domain Interface Tolerance
scripts/seqtol_resfile.py input_files/2I0L_A_C_V2006/2I0L_A_C_V2006.pdb "PIKAA ADEFGHIKLMNPQRSTVWY" B:2002 B:2003 B:2004 B:2005 B:2006
scripts/seqtol_resfile.py input_files/2IWP_B_A_V1927/2IWP_B_A_V1927.pdb "PIKAA ADEFGHIKLMNPQRSTVWY" B:1923 B:1924 B:1925 B:1926 B:1927
scripts/seqtol_resfile.py input_files/2FNE_A_C_V2048/2FNE_A_C_V2048.pdb "PIKAA ADEFGHIKLMNPQRSTVWY" B:2044 B:2045 B:2046 B:2047 B:2048
scripts/seqtol_resfile.py input_files/1N7T/1N7T_01.pdb "PIKAA ADEFGHIKLMNPQRSTVWY" B:303 B:304 B:305 B:306 B:307
mv input_files/1N7T/1N7T_01_seqtol.resfile input_files/1N7T/1N7T_seqtol.resfile
cp input_files/1N7T/1N7T_seqtol.resfile input_files/1N7T_V83K/1N7T_V83K_seqtol.resfile 
# hGH/hGHR Interface Tolerance
scripts/seqtol_resfile.py input_files/1A22_1/1A22_1.pdb "PIKAA ADEFGHIKLMNPQRSTVWY" A:14 A:28 A:47 A:61 A:171 A:179
scripts/seqtol_resfile.py input_files/1A22_2/1A22_2.pdb "PIKAA ADEFGHIKLMNPQRSTVWY" A:18 A:42 A:62 A:65 A:164 A:175
scripts/seqtol_resfile.py input_files/1A22_3/1A22_3.pdb "PIKAA ADEFGHIKLMNPQRSTVWY" A:21 A:29 A:45 A:60 A:67 A:178
scripts/seqtol_resfile.py input_files/1A22_4/1A22_4.pdb "PIKAA ADEFGHIKLMNPQRSTVWY" A:22 A:43 A:66 A:167 A:176 A:183
scripts/seqtol_resfile.py input_files/1A22_5/1A22_5.pdb "PIKAA ADEFGHIKLMNPQRSTVWY" A:26 A:44 A:48 A:64 A:168 A:174
scripts/seqtol_resfile.py input_files/1A22_6/1A22_6.pdb "PIKAA ADEFGHIKLMNPQRSTVWY" A:25 A:41 A:46 A:63 A:172

# Python command lines
# GB1 Fold Stability Tolerance
scripts/backrub_seqtol_2QMT.py input_files/2QMT/2QMT.pdb 1
scripts/backrub_seqtol_2QMT.py input_files/2QMT/2QMT.pdb 2
# ...
# PDZ Domain Interface Tolerance
scripts/backrub_seqtol.py input_files/2I0L_A_C_V2006/2I0L_A_C_V2006.pdb 1
scripts/backrub_seqtol.py input_files/2I0L_A_C_V2006/2I0L_A_C_V2006.pdb 2
# ...
scripts/backrub_seqtol.py input_files/1N7T/1N7T_%02i.pdb 1 input_files/1N7T_V83K/1N7T_V83K
scripts/backrub_seqtol.py input_files/1N7T/1N7T_%02i.pdb 2 input_files/1N7T_V83K/1N7T_V83K
# ...
# hGH/hGHR Interface Tolerance
scripts/backrub_seqtol_1A22.py input_files/1A22_1/1A22_1.pdb 1
scripts/backrub_seqtol_1A22.py input_files/1A22_1/1A22_1.pdb 2
# ...

# Sun Grid Engine qsub lines
# GB1 Fold Stability Tolerance
qsub -v PDB_PATH=input_files/2QMT/2QMT.pdb -t 1-200 -N bs_2QMT scripts/backrub_seqtol.py
# PDZ Domain Interface Tolerance
qsub -v PDB_PATH=input_files/2I0L_A_C_V2006/2I0L_A_C_V2006.pdb -t 1-200 -N bs_2I0L_A_C_V2006 scripts/backrub_seqtol.py
qsub -v PDB_PATH=input_files/2IWP_B_A_V1927/2IWP_B_A_V1927.pdb -t 1-200 -N bs_2IWP_B_A_V1927 scripts/backrub_seqtol.py
qsub -v PDB_PATH=input_files/2FNE_A_C_V2048/2FNE_A_C_V2048.pdb -t 1-200 -N bs_2FNE_A_C_V2048 scripts/backrub_seqtol.py
qsub -v PDB_PATH=input_files/1N7T/1N7T_%02i.pdb -v INPUT_PATH=input_files/1N7T/1N7T -t 1-200 -N bs_1N7T scripts/backrub_seqtol.py
qsub -v PDB_PATH=input_files/1N7T/1N7T_%02i.pdb -v INPUT_PATH=input_files/1N7T_V83K/1N7T_V83K -t 1-200 -N bs_1N7T_V83K scripts/backrub_seqtol.py
# hGH/hGHR Interface Tolerance
qsub -v PDB_PATH=input_files/1A22_1/1A22_1.pdb -t 1-100 -N bs_1A22_1 scripts/backrub_seqtol.py
qsub -v PDB_PATH=input_files/1A22_2/1A22_2.pdb -t 1-100 -N bs_1A22_2 scripts/backrub_seqtol.py
qsub -v PDB_PATH=input_files/1A22_3/1A22_3.pdb -t 1-100 -N bs_1A22_3 scripts/backrub_seqtol.py
qsub -v PDB_PATH=input_files/1A22_4/1A22_4.pdb -t 1-100 -N bs_1A22_4 scripts/backrub_seqtol.py
qsub -v PDB_PATH=input_files/1A22_5/1A22_5.pdb -t 1-100 -N bs_1A22_5 scripts/backrub_seqtol.py
qsub -v PDB_PATH=input_files/1A22_6/1A22_6.pdb -t 1-100 -N bs_1A22_6 scripts/backrub_seqtol.py
