#!/bin/bash
#PBS -o pseudo_dagman_PBS.out
#PBS -e pseudo_dagman_PBS.err
#PBS -l walltime=48:00:00

cd $PBS_O_WORKDIR

SWA_pseudo_dagman_continuous.py -j 100 protein_build.dag  > SWA_pseudo_dagman_continuous.out 2> SWA_pseudo_dagman_continuous.err
