#!/bin/bash -x
#SBATCH -J csrosetta

NSLOTS=$SLURM_NTASKS

module load openmpi/gcc

LOGS=logs_`echo $SLURM_JOB_ID | awk -v FS="." '{print $1}'`
mkdir -p $LOGS

echo "running on $NSLOTS cpus ..."
EXE=minirosetta.mpi.linuxgccrelease
CMDLINE="-out:level 300 -mute all_high_mpi_rank_filebuf -out:mpi_tracer_to_file $LOGS/log  -out:file:silent decoys.out @flags_denovo @flags_rasrec @flags_iterative -run:archive"
$MPI_RUN -n $NSLOTS $EXE $CMDLINE

